const currencyData =[
  {
    id : "AED",
    name :"Arab Emirates Dirham",
    symbol :"د.إ",
    conversion : 4.42,
    flag: "https://cdn.airpaz.com/nuxt/img/ae.9fd1fcb.svg",
  },
  {
    id : "AUD",
    name :"Australia Dollar",
    symbol :"A$",
    conversion :1.57,
    flag: "https://cdn.airpaz.com/nuxt/img/au.503a3a9.svg",
  },
  {
    id : "BDT",
    name :"Bangladeshi Taka",
    symbol :"Tk",
    conversion : 102.20,
    flag: "https://cdn.airpaz.com/nuxt/img/bd.5102bab.svg",
  },
  {
    id : "BND",
    symbol :"B$",
    name :"Brunei dollar",
    conversion :1.61,
    flag: "https://cdn.airpaz.com/nuxt/img/bn.1d4e609.svg",
  },
  {
    id : "CAD",
    name :"Canadian Dollar",
    conversion : 1.54 ,
    symbol :"C$",
    flag: "https://cdn.airpaz.com/nuxt/img/ca.c976442.svg",
  },
  {
    id : "CNY",
    name :"Chinese Yuan",
    conversion :7.79,
    symbol :"CN¥",
    flag: "https://cdn.airpaz.com/nuxt/img/cn.02c229d.svg",
  },
  {
    id : "EUR",
    name :"Euro",
    conversion : 1,
    symbol :"€",
    flag: "https://cdn.airpaz.com/nuxt/img/eu.ee7f471.svg",
  },
  {
    id : "GBP",
    name :"British Pound",
    conversion : 0.88,
    symbol :"£",
    flag: "https://cdn.airpaz.com/nuxt/img/gb.d3ddd60.svg",
  },
  {
    id : "HKD",
    symbol :"HK$",
    conversion :9.34,
    name :"Hongkong Dollar",
    flag: "https://cdn.airpaz.com/nuxt/img/hk.7428ec1.svg",
  },
  {
    id : "IDR",
    symbol :"Rp",
    conversion :16930.45,
    name :"Indonesia Rupiah",
    flag: "https://cdn.airpaz.com/nuxt/img/id.17b9967.svg",
  },
  {
    id : "INR",
    symbol :"₹",
    conversion :87.74,
    name :"Indian Rupee",
    flag: "https://cdn.airpaz.com/nuxt/img/in.e4ab7bd.svg",
  },
  {
    id : "JPY",
    conversion :87.74,
    name :"Japanese Yen",
    flag: "https://cdn.airpaz.com/nuxt/img/jp.3e72015.svg",
    symbol :"¥",
  },
  {
    id : "KHR",
    symbol :"៛",
    conversion :4898.29,
    name :"Cambodian Riel",
    flag: "https://cdn.airpaz.com/nuxt/img/kh.5a13865.svg",
  },
  {
    id : "KRW",
    name :"Korean Won",
    symbol :"₩",
    conversion :1346,
    flag: "https://cdn.airpaz.com/nuxt/img/kr.60fde7f.svg",
  },
  {
    id : "LAK",
    name :"Lao Kip",
    conversion :11253,
    symbol :"₭",
    flag: "https://cdn.airpaz.com/nuxt/img/la.0f124ae.svg",
  },
  {
    id : "LKR",
    name :"Sri Lankan Rupee",
    conversion :233.15,
    symbol :"Rs",
    flag: "https://cdn.airpaz.com/nuxt/img/lk.497ee5b.svg",
  },
  {
    id : "MMK",
    name :"Burmese Kyat",
    conversion :1601 ,
    symbol :"K",
    flag: "https://cdn.airpaz.com/nuxt/img/mm.92e9f83.svg",
  },
  {
    id : "MOP",
    name :"Macau Pataca",
    conversion :9.62,
    symbol :"MOP$",
    flag: "https://cdn.airpaz.com/nuxt/img/mo.e117885.svg",
  },
  {
    id : "MYR",
    name :"Malaysian Ringgit",
    conversion :4.90,
    symbol :"RM",
    flag: "https://cdn.airpaz.com/nuxt/img/my.e6739f4.svg",
  },
  {
    id : "NPR",
    name :"Nepalese Rupee",
    conversion :141.04 ,
    symbol :"Rs",
    flag: "https://cdn.airpaz.com/nuxt/img/np.b66578a.svg",
  },
  {
    id : "NZD",
    name :"New Zealand Dollar",
    conversion :1.67,
    symbol :"NZ$",
    flag: "https://cdn.airpaz.com/nuxt/img/nz.3241e92.svg",
  },
  {
    id : "PHP",
    name :"Philippine Peso",
    conversion :57.90,
    symbol :"₱",
    flag: "https://cdn.airpaz.com/nuxt/img/ph.12f36ee.svg",
  },
  {
    id : "RUB",
    name :"Russian Ruble",
    conversion :89.89,
    symbol :"₽",
    flag: "https://cdn.airpaz.com/nuxt/img/ru.0cacf46.svg",
  },
  {
    id : "SAR",
    symbol :"ر.س",
    name :"Saudi Arabian Riyal",
    conversion :4.52,
    flag: "https://cdn.airpaz.com/nuxt/img/sa.c36d199.svg",
  },
  {
    id : "SGD",
    symbol :"S$",
    name :"Singapore Dollar",
    conversion :1.61,
    flag: "https://cdn.airpaz.com/nuxt/img/sg.5e6ed3f.svg",
  },
  {
    id : "THB",
    name :"Thailand Baht",
    conversion :36.20,
    symbol :"฿",
    flag: "https://cdn.airpaz.com/nuxt/img/th.76fca72.svg",
  },
  {
    id : "TWD",
    name :"Taiwan Dollar",
    conversion :33.75,
    symbol :"NT$",
    flag: "https://cdn.airpaz.com/nuxt/img/tw.8a19468.svg",
  },
  {
    id : "USU",
    name :"United states Dollar",
    conversion :66.40,
    symbol :"US$",
    flag: "https://cdn.airpaz.com/nuxt/img/us.ae65659.svg",
  },
  {
    id : "VND",
    name :"Vietnam Dong",
    conversion :27978,
    symbol :"₫",
    flag: "https://cdn.airpaz.com/nuxt/img/vn.6b3aef5.svg",
  }
]
const languageData =[
  {
    src : "https://cdn.airpaz.com/nuxt/img/gb.d3ddd60.svg",
    name : "English",
    id :"EN",
  },
  {
    src :"https://cdn.airpaz.com/nuxt/img/id.17b9967.svg",
    name : "Indonesia",
    id :"ID",
  },
  {
    src : "https://cdn.airpaz.com/nuxt/img/ph.12f36ee.svg",
    name : "Tagalog",
    id :"TL",
  },
  {
    src : "https://cdn.airpaz.com/nuxt/img/cn.02c229d.svg",
    name : "简体中文",
    id :"ZH",
  },
  {
    src : "https://cdn.airpaz.com/nuxt/img/tw.8a19468.svg",
    name : "繁體中文",
    id :"ZH-TW",
  },
  {
    src :"https://cdn.airpaz.com/nuxt/img/th.76fca72.svg",
    name : "ภาษาไทย",
    id :"TH",
  },
  {
    src : "https://cdn.airpaz.com/nuxt/img/jp.3e72015.svg",
    name : "日本語",
    id :"JA",
  },
  {
    src : "https://cdn.airpaz.com/nuxt/img/kr.60fde7f.svg",
    name : "한국어",
    id :"KO",
  },
  {
    src : "https://cdn.airpaz.com/nuxt/img/my.e6739f4.svg",
    name : "Malay",
    id :"MS",
  },
  {
    src : "https://cdn.airpaz.com/nuxt/img/vn.6b3aef5.svg",
    name : "Tiếng Việt",
    id :"VI",
  }
]
const promo=[
  {
    img : "https://cdn.airpaz.com/banner/15102020_5f880792e513b.jpg",
    link :"Carefree Travelling at Airpaz with Paylater by Indodana everyday. Enjoy special discount up to IDR 500.000",
    text :"Holidays are even more memorable at AIRPAZ with Paylater by Indodana. Enjoy special discounts up to. IDR 500,000.",
    promoPeriod :"16 October 2020",
    travelerPeriod : "16 April 2021",
    topic : [
      "Promo Period 16 October 2020 - 16 April 2021",
      "Booking can be made through Airpaz website or mobile app"
    ],
    content : [
      "Promo period starts from 16 October 2020 – 16 April 2021",
      "Travel period: Anytime",
      "Discount 50% maximum Rp 50.000 using IRPAZ50 Promo Code in Indodana page with minimum transaction of Rp 500.000,-",
      "Discount 5% maximum Rp 500.000 using IRPAZ5 Promo Code in Indodana page with minimum transaction of Rp 1.000.000,-",
      "Valid for all types of airlines and hotel",
      "Valid for domestic and international flight",
      "Valid for all type of rooms and hotel",
      "Valid only for round trip flight in a single trip",
      "Payment must be in Indonesian Rupiah",
      "Payment must use PayLater by Indodana",
      "Valid for one-time transaction only for each email/ Indodana user ID during promo period",
      "Booking can be done through Airpaz website or mobile app",
      "Booking with promo applied cannot be refunded",
      "Promo cannot be combined with another promo",
      "Terms and conditions of this promo may change overtime",
      "Airpaz and Indodana have the right to cancel the discount if the transaction does not meet terms and conditions of the promo",
    ],
    discount :[
    ],
  },
  {
    img : "https://cdn.airpaz.com/banner/New-Fresh-Start-2021-LP.jpg",
    link :"New Fresh Start KTC",
    text :"Enjoy the benefit of special discount up to THB 150 everyday at AIRPAZ for KTC credit card user.",
    promoPeriod :"01 January 2021",
    travelerPeriod : "30 April 2021",
    content : [
      "Promo Period: 01 January - 30 April 2021",
      "Travel period: Anytime",
      "This promotion is valid for everyday.",
      "Discount THB 150 using NEWAPZKTC150 Promo Code with minimum transaction of THB 2000",
      "This promotion is valid for Participating Airlines : AirAsia (AK), Nok Air (DD),Malaysia Airlines (MH), Thai Lion Air (SL), Thai Airways (TG), Thai Viet Jet Air (VZ), Bangkok Airlines (PG), Thai Smile Air (WE), AirAsia Thailand (FD), Thai AirAsia X (XJ)",
      "This promotion is valid for both domestic and international routes.",
      "This promotion is valid for one way and/or round-trip flights.",
      "This promotion is valid for payment using KTC Creditcard all type",
      "This promotion is valid for one-time use per cardholder per month during the promo period.",
      "Booking can be done through our Website, Mobile site, or Application (Android/iOS).",
      "This promotion is non-transferable and non-cumulative and cannot be used in conjunction with any other discounts, vouchers, privileges or promotions (unless otherwise specified).",
      "The promotion cannot be exchanged for cash or other products.",
      "The qualifying and participating Cardholders are bound by the terms and conditions of Airpaz and KTC.",
      "Airpaz and KTC reserves the right to terminate, amend or add to any of these terms and conditions from time to time with at least five (5) calendar days’ notice to Cardholders before the new terms and conditions take effect.",
      "Airpaz and KTC reserves the right to cancel the discount if it is not in accordance with these Terms & Conditions.",
    ],
    topic : [
      "Promo Period 01 January 2021 - 30 April 2021",
      "Booking can be made through Airpaz website or mobile app",
      "Promo is applicable to all payment method using THB / Thailand Baht",
    ],
    discount :[
      {
        priceDiscount : 150,
        code : "NEWAPZKTC150",
      },
    ],
  },
  {
    img : "https://cdn.airpaz.com/banner/Cheap-Flights,-Flight-Ticket-Booking-&-Flight-Promotion-to-All-Destinations-in-February-using-Airpaz-LP-3014.jpg",
    link :"Flight Discount Up To THB 220",
    text :"",
    promoPeriod :"01 February 2021",
    travelerPeriod : "28 February 2021",
    content : [
      "Promo period: 1st February - 28th February 2021",
      "Travel period: Anytime",
      "Discount ฿20,00 using THFFEB20 Promo Code with no minimum transaction for all airlines",
      "Discount ฿75,00 using THFFEB75 Promo Code with minimum transaction of ฿2.500,00 for all airlines",
      "Discount ฿220,00 using THFFEB220 Promo Code with minimum transaction of ฿4.500,00",
      "Promo Code THFFEB220 valid for flight by AirAsia (AK), NokAir (DD), Thai AirAsia (FD), Thai AirAsia X (XJ), Thai Smile (WE), Thai Lion Air (SL), Thai Vietjet (VZ)",
      "Valid for domestic and international flight",
      "Applicable for round trip and one way booking",
      "Payment must be in THB/ Thai Baht",
      "Valid for all type of payment methods",
      "Booking must be done through Airpaz website",
      "Booking with promo applied will be non-refundable",
      "Cannot be combined with another promo",
      "This terms and conditions may changed overtime",
      "Airpaz has the rights to nullify the discount if your transaction doesn't meet terms and conditions of the promo",
    ],
    topic : [
      "Promo Period 01 February 2021 - 28 February 2021",
      "Booking can be made through Airpaz website or mobile app",
      "Promo is applicable to all payment method using THB / Thailand Baht, THB / Thailand Baht, THB / Thailand Baht",
    ],
    discount :[
      {
        priceDiscount : 20,
        code : "THFFEB20",
      },
      {
        priceDiscount : 75,
        code : "THFFEB75",
      },
      {
        priceDiscount : 220,
        code : "THFFEB220",
      },
    ],
  },
  {
    img : "https://cdn.airpaz.com/banner/Cheap-Flights-Booking-and-Airlines-Promo-to-All-Destinations-in-February-Airpaz-LP-9912.jpg",
    link :"Flight Discount Up To PHP 190",
    text :"",
    promoPeriod :"01 Feb - 28 Feb 2021",
    travelerPeriod : "01 Feb 2021 - 31 Dec 2022",
    content : [
      "Promo period: 1st February - 28th February 2021",
      "Travel period: Anytime",
      "Discount ₱20.00 using PHFFEB20 Promo Code with no minimum transaction for all airlines",
      "Discount ₱60.00 using PHFFEB60 Promo Code with minimum transaction of ₱2,500.00 for all airlines",
      "Discount ₱190.00 using PHFFEB190 Promo Code with minimum transaction of ₱3,800.00",
      "Promo Code PHFFEB190 valid for flight by PAL Express (2P), AirAsia Zest (Z2), Philipphine Airline (PR)",
      "Valid for domestic and international flight",
      "Applicable for round trip and one way booking",
      "Payment must be in PHP/ Philippines Peso",
      "Valid for all type of payment methods",
      "Booking must be done through Airpaz website",
      "Booking with promo applied will be non-refundable",
      "Cannot be combined with another promo",
      "This terms and conditions may changed overtime",
      "Airpaz has the rights to nullify the discount if your transaction doesn't meet terms and conditions of the promo",
    ],
    topic : [
      "Promo Period 01 February 2021 - 28 February 2021",
      "Booking can be made through Airpaz website or mobile app",
      "Promo is applicable to all payment method using PHP / Philippine Peso, PHP / Philippine Peso, PHP / Philippine Peso",
    ],
    discount :[
      {
        priceDiscount : 20,
        code : "PHFFEB20",
      },
      {
        priceDiscount : 60,
        code : "PHFFEB60",
      },
      {
        priceDiscount : 190,
        code : "PHFFEB190",
      },
    ],
  },
  {
    img : "https://cdn.airpaz.com/banner/Cheap-Airline-and-Flight-Tickets-Booking-to-All-Destinations-in-February-with-Airpaz-LP-1930.jpg",
    link :"Flight Discount Up To VND 80,000",
    text :"",
    promoPeriod :"01 Feb - 28 Feb 2021",
    travelerPeriod : "01 Feb 2021 - 31 Dec 2022",
    content : [
      "Promo period: 1st February - 28th February 2021",
      "Travel period: Anytime",
      "Discount 10.000 ₫ using VNFFEB10 Promo Code with no minimum transaction for all airlines",
      "Discount 25.000 ₫ using VNFFEB25 Promo Code with minimum transaction of 1.250.000 ₫ for all airlines",
      "Discount 80.000 ₫ using VNFFEB80 Promo Code with minimum transaction of 2.500.000 ₫",
      "Promo Code VNFFEB80 valid for flight by Air China (CA), Royal Brunei Airlines (BI), Thai VietJet Air (VZ), VietJet Air (VJ), Vietnam Airlines (VN)",
      "Valid for domestic and international flight",
      "Applicable for round trip and one way booking",
      "Payment must be in VND / Vietnam Dong",
      "Valid for all type of payment methods",
      "Booking must be done through Airpaz website",
      "Booking with promo applied will be non-refundable",
      "Cannot be combined with another promo",
      "This terms and conditions may changed overtime",
      "Airpaz has the rights to nullify the discount if your transaction doesn't meet terms and conditions of the promo",
    ],
    topic : [
      'Promo Period 01 February 2021 - 28 February 2021',
      "Booking can be made through Airpaz website or mobile app",
      "Promo is applicable to all payment method using VND / Vietnam Dong, VND / Vietnam Dong, VND / Vietnam Dong",
    ],
    discount :[
      {
        priceDiscount : 10000,
        code : "VNFFEB10",
      },
      {
        priceDiscount : 25000,
        code : "VNFFEB25",
      },
      {
        priceDiscount : 80000,
        code : "VNFFEB80",
      },
    ],
  },
  {
    img : "https://cdn.airpaz.com/banner/Cheap-Flight-Ticket-Online-Booking-Promo-Anyhere-Anytime-in-February-Airpaz-LP-668.jpg",
    link :"Flight Discount Up To RM 22",
    text :"",
    promoPeriod :"01 Feb - 28 Feb 2021",
    travelerPeriod : "01 Feb 2021 - 31 Dec 2022",
    content : [
      "Promo period: 1st February - 28th February 2021",
      "Travel period: Anytime",
      "Discount RM5 using MYFFEB5 Promo Code with no minimum transaction for all airlines",
      "Discount RM10 using MYFFEB10 Promo Code with minimum transaction of RM300 for all airlines",
      "Discount RM22 using MYFFEB22 Promo Code with minimum transaction of RM600",
      "Promo Code MYFFEB22 valid for flight by AirAsia (AK), AirAsia X (D7), AirAsia Zest (Z2), Garuda Indonesia (GA), Indonesia AirAsia (QZ), Jetstar Asia Airways (3K), Lion Air (JT), Malaysia Airlines (MH), Malindo (OD), Scoot (TR)",
      "Valid for domestic and international flight",
      "Applicable for round trip and one way booking",
      "Payment must be in MYR / Malaysian Ringgit",
      "Valid for all type of payment methods",
      "Booking must be done through Airpaz website",
      "Booking with promo applied will be non-refundable",
      "Cannot be combined with another promo",
      "This terms and conditions may changed overtime",
      "Airpaz has the rights to nullify the discount if your transaction doesn't meet terms and conditions of the promo",
    ],
    topic : [
      "Promo Period 01 February 2021 - 28 February 2021",
      "Booking can be made through Airpaz website or mobile app",
      "Promo is applicable to all payment method using MYR / Malaysian Ringgit, MYR / Malaysian Ringgit, MYR / Malaysian Ringgit",
    ],
    discount :[
      {
        priceDiscount : 5,
        code : "MYFFEB5",
      },
      {
        priceDiscount : 10,
        code : "MYFFEB10",
      },
      {
        priceDiscount : 22,
        code : "MYFFEB22",
      },
    ],
  },
  {
    img : "https://cdn.airpaz.com/banner/Cheap-Flight-Ticket-Booking-Promotion-Price-to-All-Destinations-in-February-Airpaz-LP-3182.jpg",
    link :"Flight Discount Up To SGD 8",
    text :"",
    promoPeriod :"01 Feb - 28 Feb 2021",
    travelerPeriod : "01 Feb 2021 - 31 Dec 2022",
    content : [
      "Promo period: 1st February - 28th February 2021",
      "Travel period: Anytime",
      "Discount $2,00 using SGFFEB2 Promo Code with no minimum transaction for all airlines",
      "Discount $8,00 using SGFFEB8 Promo Code with minimum transaction of $150,00",
      "Promo Code SGFFEB8 valid for flight by AirAsia (AK), Indonesia AirAsia (QZ), Jetstar Asia (3K), Scoot Tiger Air (TR), Thai AirAsia (FD), Thai Lion Air (SL)",
      "Valid for domestic and international flight",
      "Applicable for round trip and one way booking",
      "Payment must be in SGD / Singapore Dollar",
      "Valid for all type of payment methods",
      "Booking must be done through Airpaz website",
      "Booking with promo applied will be non-refundable",
      "Cannot be combined with another promo",
      "This terms and conditions may changed overtime",
      "Airpaz has the rights to nullify the discount if your transaction doesn't meet terms and conditions of the promo",
    ],
    topic : [
      "Promo Period 01 February 2021 - 28 February 2021",
      "Booking can be made through Airpaz website or mobile app",
      "Promo is applicable to all payment method using SGD / Singapore Dollar, SGD / Singapore Dollar",
    ],
    discount :[
      {
        priceDiscount : 2,
        code : "SGFFEB2",
      },
      {
        priceDiscount : 8,
        code : "SGFFEB8",
      },
    ],
  },
  {
    img : "https://cdn.airpaz.com/banner/Cheap-Flight-Ticket-Promo-to-All-Destinations-for-February-Airpaz-LP-6021test1.jpg",
    link :"Flight Discount Up To Rp 88.000,-",
    text :"",
    promoPeriod :"01 Feb - 28 Feb 2021",
    travelerPeriod : "01 Feb 2021 - 31 Dec 2022",
    content : [
      "Promo period: 1st February - 28th February 2021",
      "Travel period: Anytime",
      "Discount Rp10.000,00 using IDFFEB10 Promo Code with no minimum transaction for all airlines",
      "Discount Rp25.720,00 using IDFFEB25 Promo Code with minimum transaction of Rp1.250.000 for all airlines",
      "Discount Rp88.000,00 using IDFFEB88 Promo Code with minimum transaction of Rp3.000.000",
      "Promo Code IDFFEB88 valid for flight by AirAsia (AK), AirAsia Indonesia (QZ), AirAsia x (D7), Garuda Indonesia (GA), Nam Air (IN), Sriwijaya Air (SJ), Thai AirAsia (FD)",
      "Valid for domestic and international flight",
      "Applicable for round trip and one way booking",
      "Payment must be in IDR / Indonesian Rupiah",
      "Valid for all type of payment methods",
      "Booking must be done through Airpaz website",
      "Booking with promo applied will be non-refundable",
      "Cannot be combined with another promo",
      "This terms and conditions may changed overtime",
      "Airpaz has the rights to nullify the discount if your transaction doesn't meet terms and conditions of the promo",
    ],
    topic : [
      "Promo Period 01 February 2021 - 28 February 2021",
      "Booking can be made through Airpaz website or mobile app",
      "Promo is applicable to all payment method using IDR / Indonesian Rupiah, IDR / Indonesian Rupiah, IDR / Indonesian Rupiah",
    ],
    discount :[
      {
        priceDiscount : 10000,
        code : "IDFFEB10",
      },
      {
        priceDiscount : 25720,
        code : "IDFFEB25",
      },
      {
        priceDiscount : 88000,
        code : "IDFFEB88",
      },
    ],
  },
]
const codeDiscount = [];
const tripDataVN ={
  countryTrip : "VietNam",
  detailTrip : [
  {
    id : "SGN",
    name : "Ho Chi Minh City",
    from : "Ho Chi Minh",
    airport : "Tan Son Nhat International Airport",
    fly : [
      {
        key : "2124",
        to : "Hanoi",
        toId : "HAN",
        toAirline : "NoiBai International Airport",
        img : "url(/img/city-1.jpeg)" ,
        id: "",
          price : 120,
          currency : "€",
          typePrice : "normal",
          flightTime : 2.0,
          departureTime : "7:00",
          destinationTime : "9:00",
          direct :"",
          baggage : "",
          typePlane: "",
      },
      {
        key : "2112324",
        to : "DaNang",
        toAirline : "Da Nang International Airport",
        toId :"DAD",
        img : "url(/img/city-2.jpeg)" ,
        id: "",
          price : 160,
          currency : "€",
          typePrice : "normal",
          flightTime : 2.0,
          departureTime : "10:00",
          destinationTime : "12:00",
          direct :"",
          baggage : "",
          typePlane: "",
      },
    ],
  },
  {
    id : "HAN",
    name : "Hanoi",
    from : "Hanoi",
    airport : "Noi Bai International Airport",
    fly : [
      {
        key : "21as124",
        to : "Ho Chi Minh",
        toId : "SGN",
        toAirline : "Tan Son Nhat International Airport",
        img : "url(/img/city-6.jpeg)" ,
        id: "",
          price : 120,
          currency : "€",
          typePrice : "normal",
          flightTime : 2.0,
          departureTime : "7:00",
          destinationTime : "9:00",
          direct :"",
          baggage : "",
          typePlane: "",
      },
      {
        key : "2as24",
        to : "PhuQuoc",
        toAirline : "Phu Quoc International Airport",
        toId:"PQV",
        img : "url(/img/city-4.webp)" ,
          price : 600,
          currency : "€",
          typePrice : "business",
          flightTime : 4.0,
          departureTime : "2:00",
          destinationTime : "6:00",
          direct :"",
          baggage : "", 
          typePlane: "",
      },
    ],
  },
  {
    id : "DAD",
    name : "Da Nang",
    from : "DaNang",
    airport : "Da Nang International Airport",
    fly : [
      {
        key : "21123p4",
        to : "Cuba",
        toAirline : "Tan Son Nhat International Airport",
        toId :"CBA",
        img : "url(/img/city-2.jpeg)" ,
        id: "",
          price : 160,
          currency : "€",
          typePrice : "normal",
          flightTime : 2.0,
          departureTime : "10:00",
          destinationTime : "12:00",
          direct :"",
          baggage : "",
          typePlane: "",
      },
    ],
  }
]}
const tripDataUS ={
  countryTrip : "American",
  detailTrip : [
    {
      id : "AMR",
      name : "Denver City",
      from : "Denver",
      airport : "Denver - Den International Airport",
      fly : [
        {
          key : "a123",
          to : "NewYork",
          toAirline : "NewYork International Airport",
          img : "url(/img/city-7.jpeg)" ,
          toId: "NYC",
          price : 230,
          currency : "€",
          typePrice : "normal",
          flightTime : 5.0,
          departureTime : "0:00",
          destinationTime : "5:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
        {
          key : "a1223",
          to : "Paris",
          toAirline : "Paris International Airport",
          img : "url(/img/city-8.jpeg)" ,
          toId: "PAR",
          price : 670,
          currency : "€",
          typePrice : "business",
          flightTime : 3.0,
          departureTime : "13:00",
          destinationTime : "16:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
      ],
    },
    {
      id : "DAF",
      name : "Texas City",
      from : "Texas",
      airport : "Dallas-Forth Worth International Airport",
      fly : [
        {
          key : "a1213",
          to : "Dubai",
          toAirline : "Dubai International Airport",
          img : "url(/img/city-9.jpeg)" ,
          toId: "DUB",
          price : 240,
          currency : "€",
          typePrice : "normal",
          flightTime : 3.0,
          departureTime : "12:00",
          destinationTime : "15:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
        {
          key : "a11123",
          to : "California",
          toAirline : "California International Airport",
          img : "url(/img/city-10.jpeg)" ,
          toId: "CAL",
          price : 310,
          currency : "€",
          typePrice : "normal",
          flightTime : 6.0,
          departureTime : "3:00",
          destinationTime : "9:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
      ],
    },
    {
      id : "ATL  ",
      name : "Georgia City",
      from :"Georgia",
      airport : "Atlanta  International Airport",
      fly : [
        {
          key : "a123a",
          to : "Tokio",
          toAirline : "Tokio International Airport",
          img : "url(/img/city-11.jpeg)" ,
          toId: "TOK",
          price : 190,
          currency : "€",
          typePrice : "normal",
          flightTime : 2.0,
          departureTime : "17:00",
          destinationTime : "19:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
        {
          key : "a12aa3",
          to : "HongKong",
          toAirline : "HongKong International Airport",
          img : "url(/img/city-12.jpeg)" ,
          toId: "HOK",
          price : 890,
          currency : "€",
          typePrice : "business",
          flightTime : 5.0,
          departureTime : "11:00",
          destinationTime : "16:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
      ],
    }
  ]
}
const tripDataUK ={
  countryTrip : "United Kingdom",
  detailTrip : [
    {
      id : "BA",
      name : "British City",
      from : "British",
      airport : "British Airways International Airport",
      fly : [
        {
          key : "ab1sd23",
          to : "Singapore",
          toAirline : "Singapore International Airport",
          img : "url(/img/city-13.jpeg)" ,
          toId: "SIN",
          price : 220,
          currency : "€",
          typePrice : "normal",
          flightTime : 4.0,
          departureTime : "5:00",
          destinationTime : "9:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
        {
          key : "64512",
          to : "ThaiLand",
          toAirline : "Thailand International Airport",
          img : "url(/img/city-14.jpeg)" ,
          toId: "THL",
          price : 180,
          currency : "€",
          typePrice : "normal",
          flightTime : 1.5,
          departureTime : "1:00",
          destinationTime : "2:30",
          direct :"",
          baggage : "",
          typePlane: "",
        },
      ],
    },
    {
      id : "ABB",
      name : "Abingdon City",
      from : "Abingdon",
      airport : "RAF Abingdon International Airport",
      fly : [
        {
          key : "6a4512",
          to : "Cuba",
          toAirline : "Cuba International Airport",
          img : "url(/img/city-15.jpeg)" ,
          toId: "CUB",
          price : 320,
          currency : "€",
          typePrice : "normal",
          flightTime : 5.0,
          departureTime : "10:15",
          destinationTime : "16:15",
          direct :"",
          baggage : "",
          typePlane: "",
        },
        {
          key : "6451aa2",
          to : "China",
          toAirline : "China International Airport",
          img : "url(/img/city-16.webp)" ,
          toId: "CHN",
          price : 234,
          currency : "€",
          typePrice : "normal",
          flightTime : 3.0,
          departureTime : "16:00",
          destinationTime : "19:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
      ],
    },
    {
      id : "EGDM",
      name : "Amesbury City",
      from :"Amesbury",
      airport : "MoD Boscombe Down  International Airport",
      fly : [
        {
          key : "64512cc",
          to : "Texas",
          toAirline : "Texas International Airport",
          img : "url(/img/city-18.webp)" ,
          toId: "TEX",
          price : 220,
          currency : "€",
          typePrice : "normal",
          flightTime : 3.0,
          departureTime : "11:00",
          destinationTime : "14:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
      ],
    }
  ]
}
const tripDataJa ={
  countryTrip : "Japan",
  detailTrip : [
    {
      id : "KIX",
      name : "Osaka City",
      from : "Osaka",
      airport : "Izumisano International Airport",
      fly : [
        {
          key : "asd4512",
          to : "Indonesia",
          img : "url(/img/city-19.webp)" ,
          toId: "IND",
          toAirline : "Indonesia International Airport",
          price : 190,
          currency : "€",
          typePrice : "normal",
          flightTime : 2.0,
          departureTime : "11:30",
          destinationTime : "13:30",
          direct :"",
          baggage : "",
          typePlane: "",
        },
        {
          key : "asa512",
          to : "Australia",
          img : "url(/img/city-20.jpg)" ,
          toId: "AUS",
          price : 260,
          currency : "€",
          toAirline : "Australia International Airport",
          typePrice : "normal",
          flightTime : 4.0,
          departureTime : "14:00",
          destinationTime : "18:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
      ],
    },
    {
      id : "HND",
      name : "Tokyo City",
      from : "Tokyo",
      airport : "Ota ward, Tokyo International Airport",
      fly : [
        {
          key : "aaa64512",
          to : "Osaka",
          toAirline : "Osaka International Airport",
          img : "url(/img/city-21.webp)" ,
          toId: "OSK",
          price : 180,
          currency : "€",
          typePrice : "normal",
          flightTime : 1.25,
          departureTime : "14:00",
          destinationTime : "15:15",
          direct :"",
          baggage : "",
          typePlane: "",
        },
        {
          key : "dds12",
          to : "BangKok",
          toAirline : "BangKok International Airport",
          img : "url(/img/city-22.jpg)" ,
          toId: "BAK",
          price : 220,
          currency : "€",
          typePrice : "normal",
          flightTime : 2.0,
          departureTime : "7:00",
          destinationTime : "9:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
      ],
    },
    {
      id : "FUK ",
      name : "Fukuoka City",
      from :"Fukuoka",
      airport : "Fukuoka International Airport",
      fly : [
        {
          key : "645aa",
          to : "Lao Kai-Vietnam",
          toAirline : "Lao Kai International Airport",
          img : "url(/img/city-23.webp)" ,
          toId: "CMA",
          price : 670,
          currency : "€",
          typePrice : "business",
          flightTime : 4.0,
          departureTime : "15:00",
          destinationTime : "19:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
        {
          key : "645bb",
          to : "Dong Thap-Vietnam",
          img : "url(/img/city-24.jpg)" ,
          toId: "DCL",
          price : 170,
          toAirline : "Dong Thap International Airport",
          currency : "€",
          typePrice : "normal",
          flightTime : 2.0,
          departureTime : "5:00",
          destinationTime : "7:00",
          direct :"",
          baggage : "",
          typePlane: "",
        },
      ],
    }
  ]
}
const mobileCountry =[
  {
    country : 'Afghanistan',
    number: '+93',
  },
  {
    country : 'Aland Island',
    number: '++358',
  },
  {
    country : 'Albania',
    number: '+355',
  },
  {
    country : 'Algeria',
    number: '+213',
  },
  {
    country : 'American',
    number: '+1684',
  },
  {
    country : 'Australia',
    number: '+61',
  },
  {
    country : 'Benin',
    number: '+299',
  },
]
const debug =[
  {
    type : '',
    description : '',
  },
]
const listLanguage ={
  vietnamese :{
    flight : 'Chuyến bay',
    allTrip : 'Tất cả chuyến đi',
    promo : 'Khuyến mãi',
    more : 'Thông tin khác',
    login : 'Đăng nhập',
    register : 'Đăng ký',
    oneWay : 'Một chiều',
    roundTrip : 'Chuyến khứ hồi',
    from : 'Từ',
    to : 'Đến',
    selectDepartureCity : 'Chọn điểm khởi hành',
    selectDestinationCity : 'Chọn điểm đến',
    departureDate : 'Ngày khởi hành',
    destinationDate : 'Ngày trở về',
    traveler : 'Hành khách',
    search : 'Tìm kiếm',
    recommend : 'Gợi ý cho bạn',
    airlinePartner :'Các hãng hàng không đối tác',
    paymentPartner : 'Phương thức thanh toán được chấp nhận',
    popularFlight : 'Các chuyến bay phổ biến',
    flightTo : 'Chuyến bay đến',
    topFlight : 'Lộ trình bay dẫn đầu',
    adult : 'Người lớn',
    children : 'Trẻ nhỏ',
    infant : 'Con nít',
    age : 'Tuổi',
    textHeadFlight : 'Dễ dàng tìm kiếm, so sánh và đặt chuyến bay của bạn',
    textFooterFirst : "Tải xuống ứng dụng DreamAirline ngay bây giờ,",
    textFooterSecond :'Đặt khách sạn và vé máy bay mà không gặp rắc rối!',
    subscribe : 'ĐĂNG KÝ',
    enterEmail : 'Nhập địa chỉ email',
    account : 'Tài khoản',
    support : 'Hổ trợ',
    followUs : "Theo dõi hãng bay",
    signUpForNewsletter : 'Đăng ký để nhận Bản Tin',
    subscribeTextFooter : 'Đăng ký để nhận ưu đãi và cập nhật trong emai của bạn',
    startFrom : 'Bắt đầu từ',
    seePopular : 'Xem các địa điểm phổ biến',
    filter : 'Bộ lọc',
    all : 'Tất cả',
    sort : 'Cú pháp ngắn',
    plane : 'Tên máy bay',
    stop : 'trạm dừng',
    departure :'Thời điểm khởi hành',
    typePrice : 'Hạng vé',
    direct :'Bay thẳng',
    transit : 'Quá cảnh',
    oneStop : 'Một điểm dừng',
    normal : 'Hạng thường',
    business : 'Hạng thương gia',
    earlyFlight : 'Chuyến bay sớm',
    morningFLight : 'Chuyến bay sáng',
    afternoonFlight :"Chuyến bay chiều",
    nightFlight : 'Chuyến bay đêm',
    lowestPrice : 'Giá thấp nhất',
    highestPrice : 'Giá cao nhất',
    earliest : 'Chuyến sớm nhất',
    lastest :'Chuyến muộn nhất',
    promoList : 'Danh sách khuyến mãi',
    moreDetail : 'Thông tin cụ thể',
    share : 'Chia sẻ với bạn bè',
    discount : 'GIẢM GIÁ',
    copy : 'Sao chép',
    term : 'Điều khoản và điều kiện',
    promoPeriod : 'Thời gian khuyến mãi',
    travelPeriod : 'Thời gian đi',
    chooseDifferentTrip : 'Chọn các chuyến đi khác nhau',
    chooseFlight : 'Chọn chuyến này',
    changeDate : 'Đổi lịch trình',
    changeSearch : 'Thay đổi tìm kiếm',
    pax : 'vé',
    departureTo : 'Chuyến bay đến',
  },
  english : {
    flight : 'Flight',
    allTrip : 'All Trips',
    promo : 'Promo',
    more : 'More',
    login : 'Login',
    register : 'Register',
    oneWay : 'One Way',
    roundTrip : 'Round Trip',
    from : 'From',
    to : 'To',
    selectDepartureCity : 'Select Departure City',
    selectDestinationCity : 'Select Destination City',
    departureDate : 'Departure Date',
    destinationDate : 'Destination Date',
    traveler : 'Traveler',
    search : 'Search',
    recommend : 'Recommended for you',
    airlinePartner :'Airline Partners',
    paymentPartner : 'Payment Partners',
    popularFlight : 'Popular Flight Destinations',
    flightTo : 'Flights to',
    topFlight : 'Top Flight Routes',
    adult : 'Adults',
    children : 'Childrens',
    infant : 'Infants',
    age : 'Age',
    textHeadFlight : 'Find, Compare and Book Your Flight Easily',
    textFooterFisrt : "Download DreamAirline App Now,",
    textFooterSecond : 'Book hotel and flight ticket without a hassle!',
    subscribe : 'SUBSCRIBE',
    enterEmail : 'Enter Email Address',
    account : 'Tài khoản',
    support : 'Hổ trợ',
    followUs : "Theo dõi hãng bay",
    signUpForNewsletter : 'Sign Up for Newsletter',
    subscribeTextFooter : 'Subscribe to get deals & update in your email',
    startFrom : 'Start from',
    seePopular : 'See Popular Places',
    filter : 'Filters',
    all : 'All',
    sort : 'Sort',
    plane : 'Plane',
    stop : 'Stops',
    departure :'Departure',
    typePrice : 'Type Ticket',
    direct :'Direct',
    transit : 'Transit',
    oneStop : 'One-stop',
    normal : 'Normal',
    business : 'Business',
    earlyFlight : 'Early Flight',
    morningFLight : 'Morning Flight',
    afternoonFlight :"Afternoon Flight",
    nightFlight : 'Night Flight',
    lowestPrice : 'Lowest Price',
    highestPrice : 'Highest Price',
    earliest : 'Earliest Trip',
    lastest :'Latest Trip',
    promoList : 'Promo List',
    moreDetail : 'More Details',
    share : 'Share with your friend',
    discount : 'DISCOUNT',
    copy : 'Copy',
    term : 'Term & Conditions',
    promoPeriod : 'Promo Period',
    travelPeriod : 'Travel Period',
    chooseDifferentTrip : 'Choose different trips',
    chooseFlight : 'Choose Flight',
    changeDate : 'Change Date',
    changeSearch : 'Change Search',
    pax : 'pax',
    departureTo : 'Departure flight to',
  }
}
const allTrip = [
  tripDataVN,
  tripDataUS,
  tripDataUK,
  tripDataJa,
]
const flyData =[]
const flyDataT =[]
const  airline =[]
const listPrice =[]
const toCountry =[]

const account =[
  {
    username : 'monday',
    pass : '1',
    name : 'Monday',
  },
  {
    username : 'tuesday',
    pass : '1',
    name : 'Tuesday',
  },
  {
    username : 'wednesday',
    pass : '1',
    name : 'Wednesday',
  },
  {
    username : 'thursday',
    pass : '1',
    name : 'Thursday',
  },
  {
    username : 'friday',
    pass : '1',
    name : 'Friday',
  },
  {
    username : 'saturday',
    pass : '1',
    name : 'Saturday',
  },
  {
    username : 'sunday',
    pass : '1',
    name : 'Sunday',
  },
]

const holiday = [
  {
    date : '1',
    month : '1',
    name : 'Tết Dương lịch',
  },
  {
    date : '14',
    month : '2',
    name : 'Lễ tình nhân',
  },
  {
    date : '27',
    month : '2',
    name : 'Ngày thầy thuốc Việt Nam',
  },
  {
    date : '8',
    month : '3',
    name : 'Ngày Quốc tế Phụ nữ',
  },
  {
    date : '20',
    month: '3',
    name : 'Ngày Quốc tế Hạnh phúc',
  },
  {
    date : '26',
    month :'3',
    name : 'Ngày thành lập Đoàn TNCS Hồ Chí Minh',
  },
  {
    date : '1',
    month : '4',
    name : 'Ngày Cá tháng Tư',
  },
  {
    date : '30',
    month :'4',
    name : 'Ngày giải phóng miền Nam',
  },
  {
    date : '1',
    month :'5',
    name : 'Ngày Quốc tế Lao động',
  },
  {
    date : '7',
    month:'5',
    name : 'Ngày chiến thắng Điện Biên Phủ',
  },
  {
    date : '13',
    month :'5',
    name : 'Ngày của mẹ',
  },
  {
    date : '19',
    month :'5',
    name : 'Ngày sinh chủ tịch Hồ Chí Minh',
  },
  {
    date : '1',
    month : '6',
    name : 'Ngày Quốc tế thiếu nhi',
  },
  {
    date : '17',
    month :"6",
    name : 'Ngày của cha',
  },
  {
    date : '21',
    month : '6',
    name : 'Ngày báo chí Việt Nam',
  },
  {
    date : '28',
    month : '6',
    name : 'Ngày gia đình Việt Nam',
  },
  {
    date : '11',
    month : '7',
    name : 'Ngày dân số thế giới',
  },
  {
    date : '27',
    month : '7',
    name : 'Ngày Thương binh liệt sĩ',
  },
  {
    date : '28',
    month : '7',
    name : 'Ngày thành lập công đoàn Việt Nam',
  },
  {
    date : '19',
    month : '8',
    name : 'Ngày tổng khởi nghĩa',
  },
  {
    date : '2',
    month : '9',
    name : 'Ngày Quốc Khánh',
  },
  {
    date : '10',
    month : '9',
    name : 'Ngày thành lập Mặt trận Tổ quốc Việt Nam',
  },
  {
    date : '1',
    month : '10',
    name : 'Ngày quốc tế người cao tuổi',
  },
  {
    date : '10',
    month : '10',
    name : 'Ngày giải phóng thủ đô',
  },
  {
    date : '13',
    month : '10',
    name : 'Ngày doanh nhân Việt Nam',
  },
  {
    date : '20',
    month : '10',
    name : 'Ngày Phụ nữ Việt Nam',
  },
  {
    date : '31',
    month : '10',
    name : 'Ngày Halloween',
  },
  {
    date : '9',
    month : '11',
    name : 'Ngày pháp luật Việt Nam',
  },
  {
    date : '19',
    month : '11',
    name : 'Ngày Quốc tế Nam giới',
  },
  {
    date : '20',
    month : '11',
    name : 'Ngày Nhà giáo Việt Nam',
  },
  {
    date : '23',
    month : '11',
    name : 'Ngày thành lập Hội chữ thập đỏ Việt Nam',
  },
  {
    date : '1',
    month : '12',
    name : 'Ngày thế giới phòng chống AIDS',
  },
  {
    date : '19',
    month : '12',
    name : 'Ngày toàn quốc kháng chiến',
  },
  {
    date : '24',
    month : '12',
    name : 'Ngày lễ Giáng sinh',
  },
  {
    date : '22',
    month : '12',
    name : 'Ngày thành lập quân đội nhân dân Việt Nam',
  },
]

export const appData={
  holiday : holiday,
  account : account,
  codeDiscount : codeDiscount,
  listLanguage : listLanguage,
  currencyData : currencyData,
  languageData : languageData,
  allTrip : allTrip,
  airline : airline,
  flyData : flyData,
  flyDataT : flyDataT,
  listPrice : listPrice,
  toCountry : toCountry,
  mobileCountry : mobileCountry,
  promo: promo,
  debug : debug,
}

function setData (){
  promo.map(data => {
    return data.discount.map(code => {
      return codeDiscount.push(code.code);
    })
  })
  allTrip.map( dataAll => {
    return dataAll.detailTrip.map(data => {
      return data.fly.map(fly => toCountry.push({to :fly.to, id : fly.toId, toAirline : fly.toAirline})) // con cho mat day khon nan tuoi lol.
    })
});
  allTrip.map( dataAll => {
      return dataAll.detailTrip.map(data => {
        return data.fly.map(fly => flyData.push(({...fly, from : data.from, id : data.id, name : data.name, airport : data.airport}))) // con cho mat day khon nan tuoi lol.
      })
  });
  flyData.map( data => {
    return flyDataT.push(({...data, departureF : parseFloat(data.departureTime)})) // con cho mat day khon nan tuoi lol.
});
  allTrip.map(dataAll =>{
    return dataAll.detailTrip.map(data =>{
      return airline.push(data.from)
    })
  });
  allTrip.map( dataAll => {
    return dataAll.detailTrip.map(data => {
      return data.fly.map(fly => {
        return listPrice.push(fly.price)
      })
    })
});
}
function LoadData(){
  setData();
}
LoadData()